"""add medical and family contact fields to cared_person

Revision ID: 0624a5cacedc
Revises: 24b0d53d3977
Create Date: 2025-06-28 23:34:48.439678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0624a5cacedc'
down_revision: Union[str, None] = '24b0d53d3977'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cared_persons', sa.Column('medical_contact_name', sa.String(length=100), nullable=True))
    op.add_column('cared_persons', sa.Column('medical_contact_phone', sa.String(length=20), nullable=True))
    op.add_column('cared_persons', sa.Column('family_contact_name', sa.String(length=100), nullable=True))
    op.add_column('cared_persons', sa.Column('family_contact_phone', sa.String(length=20), nullable=True))
    op.add_column('cared_persons', sa.Column('medical_notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cared_persons', 'medical_notes')
    op.drop_column('cared_persons', 'family_contact_phone')
    op.drop_column('cared_persons', 'family_contact_name')
    op.drop_column('cared_persons', 'medical_contact_phone')
    op.drop_column('cared_persons', 'medical_contact_name')
    # ### end Alembic commands ###
