"""add_is_self_care_to_cared_persons

Revision ID: 0ab56ac02384
Revises: b315a39aab9d
Create Date: 2025-07-20 05:41:31.027818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ab56ac02384'
down_revision: Union[str, None] = 'b315a39aab9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
