"""add_referral_types_table_and_normalize_referral_type

Revision ID: 1bef6936d69e
Revises: 5100c909bfd9
Create Date: 2025-07-06 01:00:18.859204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bef6936d69e'
down_revision: Union[str, None] = '5100c909bfd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('referral_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_referral_types_category'), 'referral_types', ['category'], unique=False)
    op.create_index(op.f('ix_referral_types_name'), 'referral_types', ['name'], unique=True)
    op.add_column('referrals', sa.Column('referral_type_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_referrals_referral_type_id'), 'referrals', ['referral_type_id'], unique=False)
    op.create_foreign_key(None, 'referrals', 'referral_types', ['referral_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'referrals', type_='foreignkey')
    op.drop_index(op.f('ix_referrals_referral_type_id'), table_name='referrals')
    op.drop_column('referrals', 'referral_type_id')
    op.drop_index(op.f('ix_referral_types_name'), table_name='referral_types')
    op.drop_index(op.f('ix_referral_types_category'), table_name='referral_types')
    op.drop_table('referral_types')
    # ### end Alembic commands ###
