"""add_status_types_table_manual

Revision ID: 3b0b703f2d25
Revises: b8ddb6ba9fb2
Create Date: 2025-07-04 21:50:36.498406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b0b703f2d25'
down_revision: Union[str, None] = 'b8ddb6ba9fb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('status_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_status_types_category'), 'status_types', ['category'], unique=False)
    op.create_index(op.f('ix_status_types_id'), 'status_types', ['id'], unique=False)
    op.create_index(op.f('ix_status_types_name'), 'status_types', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_status_types_name'), table_name='status_types')
    op.drop_index(op.f('ix_status_types_id'), table_name='status_types')
    op.drop_index(op.f('ix_status_types_category'), table_name='status_types')
    op.drop_table('status_types')
    # ### end Alembic commands ###
