"""normalize report_type in report

Revision ID: 4d6d44bd1ed4
Revises: 89fb80343f59
Create Date: 2025-07-06 00:23:20.455342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d6d44bd1ed4'
down_revision: Union[str, None] = '89fb80343f59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_types_name'), 'report_types', ['name'], unique=True)
    op.add_column('reports', sa.Column('report_type_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_reports_report_type_id'), 'reports', ['report_type_id'], unique=False)
    op.create_foreign_key(None, 'reports', 'report_types', ['report_type_id'], ['id'])
    op.drop_column('reports', 'report_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('report_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.drop_index(op.f('ix_reports_report_type_id'), table_name='reports')
    op.drop_column('reports', 'report_type_id')
    op.drop_index(op.f('ix_report_types_name'), table_name='report_types')
    op.drop_table('report_types')
    # ### end Alembic commands ###
