"""add_shift_observation_types_table_and_normalize_shift_observation_type

Revision ID: 5100c909bfd9
Revises: a71fed7c31f1
Create Date: 2025-07-06 00:57:52.019909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5100c909bfd9'
down_revision: Union[str, None] = 'a71fed7c31f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shift_observation_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shift_observation_types_category'), 'shift_observation_types', ['category'], unique=False)
    op.create_index(op.f('ix_shift_observation_types_name'), 'shift_observation_types', ['name'], unique=True)
    op.add_column('shift_observations', sa.Column('shift_observation_type_id', sa.Integer(), nullable=False, comment='Tipo de observación de turno normalizado'))
    op.create_index(op.f('ix_shift_observations_shift_observation_type_id'), 'shift_observations', ['shift_observation_type_id'], unique=False)
    op.create_foreign_key(None, 'shift_observations', 'shift_observation_types', ['shift_observation_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shift_observations', type_='foreignkey')
    op.drop_index(op.f('ix_shift_observations_shift_observation_type_id'), table_name='shift_observations')
    op.drop_column('shift_observations', 'shift_observation_type_id')
    op.drop_index(op.f('ix_shift_observation_types_name'), table_name='shift_observation_types')
    op.drop_index(op.f('ix_shift_observation_types_category'), table_name='shift_observation_types')
    op.drop_table('shift_observation_types')
    # ### end Alembic commands ###
