"""add_device_types_table_and_normalize_device_type_in_device

Revision ID: 5c426b00feb0
Revises: b2d0afa29bf3
Create Date: 2025-07-06 00:50:55.971159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c426b00feb0'
down_revision: Union[str, None] = 'b2d0afa29bf3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('icon_name', sa.String(length=50), nullable=True),
    sa.Column('color_code', sa.String(length=7), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_types_category'), 'device_types', ['category'], unique=False)
    op.create_index(op.f('ix_device_types_name'), 'device_types', ['name'], unique=True)
    op.add_column('devices', sa.Column('device_type_id', sa.Integer(), nullable=True))
    op.drop_index('ix_devices_device_type', table_name='devices')
    op.create_index(op.f('ix_devices_device_type_id'), 'devices', ['device_type_id'], unique=False)
    op.create_foreign_key(None, 'devices', 'device_types', ['device_type_id'], ['id'])
    op.drop_column('devices', 'device_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('device_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'devices', type_='foreignkey')
    op.drop_index(op.f('ix_devices_device_type_id'), table_name='devices')
    op.create_index('ix_devices_device_type', 'devices', ['device_type'], unique=False)
    op.drop_column('devices', 'device_type_id')
    op.drop_index(op.f('ix_device_types_name'), table_name='device_types')
    op.drop_index(op.f('ix_device_types_category'), table_name='device_types')
    op.drop_table('device_types')
    # ### end Alembic commands ###
