"""add_caregiver_assignment_types_table_and_normalize_caregiver_assignment_type

Revision ID: 7f59716bedbb
Revises: 1bef6936d69e
Create Date: 2025-07-06 01:03:44.566853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f59716bedbb'
down_revision: Union[str, None] = '1bef6936d69e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('caregiver_assignment_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_caregiver_assignment_types_category'), 'caregiver_assignment_types', ['category'], unique=False)
    op.create_index(op.f('ix_caregiver_assignment_types_name'), 'caregiver_assignment_types', ['name'], unique=True)
    op.add_column('caregiver_assignments', sa.Column('caregiver_assignment_type_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_caregiver_assignments_caregiver_assignment_type_id'), 'caregiver_assignments', ['caregiver_assignment_type_id'], unique=False)
    op.create_foreign_key(None, 'caregiver_assignments', 'caregiver_assignment_types', ['caregiver_assignment_type_id'], ['id'])
    op.drop_column('caregiver_assignments', 'assignment_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('caregiver_assignments', sa.Column('assignment_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'caregiver_assignments', type_='foreignkey')
    op.drop_index(op.f('ix_caregiver_assignments_caregiver_assignment_type_id'), table_name='caregiver_assignments')
    op.drop_column('caregiver_assignments', 'caregiver_assignment_type_id')
    op.drop_index(op.f('ix_caregiver_assignment_types_name'), table_name='caregiver_assignment_types')
    op.drop_index(op.f('ix_caregiver_assignment_types_category'), table_name='caregiver_assignment_types')
    op.drop_table('caregiver_assignment_types')
    # ### end Alembic commands ###
