"""normalize care_type in cared_person

Revision ID: 856efb6a597b
Revises: 1492e2d3f261
Create Date: 2025-07-06 00:15:40.035165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '856efb6a597b'
down_revision: Union[str, None] = '1492e2d3f261'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('care_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_care_types_name'), 'care_types', ['name'], unique=True)
    op.add_column('cared_persons', sa.Column('care_type_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_cared_persons_care_type_id'), 'cared_persons', ['care_type_id'], unique=False)
    op.create_foreign_key(None, 'cared_persons', 'care_types', ['care_type_id'], ['id'])
    op.drop_column('cared_persons', 'care_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cared_persons', sa.Column('care_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'cared_persons', type_='foreignkey')
    op.drop_index(op.f('ix_cared_persons_care_type_id'), table_name='cared_persons')
    op.drop_column('cared_persons', 'care_type_id')
    op.drop_index(op.f('ix_care_types_name'), table_name='care_types')
    op.drop_table('care_types')
    # ### end Alembic commands ###
