"""normalize_status_fields_phase_2

Revision ID: 881d292c26c8
Revises: 9bfe8aac1714
Create Date: 2025-07-04 22:08:00.187716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '881d292c26c8'
down_revision: Union[str, None] = '9bfe8aac1714'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cared_person_institutions', sa.Column('status_type_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_cared_person_institutions_status_type_id'), 'cared_person_institutions', ['status_type_id'], unique=False)
    op.create_foreign_key(None, 'cared_person_institutions', 'status_types', ['status_type_id'], ['id'])
    op.drop_column('cared_person_institutions', 'status')
    op.add_column('caregiver_institutions', sa.Column('status_type_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_caregiver_institutions_status_type_id'), 'caregiver_institutions', ['status_type_id'], unique=False)
    op.create_foreign_key(None, 'caregiver_institutions', 'status_types', ['status_type_id'], ['id'])
    op.drop_column('caregiver_institutions', 'status')
    op.add_column('restraint_protocols', sa.Column('status_type_id', sa.Integer(), nullable=True))
    op.drop_index('ix_restraint_protocols_status', table_name='restraint_protocols')
    op.create_index(op.f('ix_restraint_protocols_status_type_id'), 'restraint_protocols', ['status_type_id'], unique=False)
    op.create_foreign_key(None, 'restraint_protocols', 'status_types', ['status_type_id'], ['id'])
    op.drop_column('restraint_protocols', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restraint_protocols', sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'restraint_protocols', type_='foreignkey')
    op.drop_index(op.f('ix_restraint_protocols_status_type_id'), table_name='restraint_protocols')
    op.create_index('ix_restraint_protocols_status', 'restraint_protocols', ['status'], unique=False)
    op.drop_column('restraint_protocols', 'status_type_id')
    op.add_column('caregiver_institutions', sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'caregiver_institutions', type_='foreignkey')
    op.drop_index(op.f('ix_caregiver_institutions_status_type_id'), table_name='caregiver_institutions')
    op.drop_column('caregiver_institutions', 'status_type_id')
    op.add_column('cared_person_institutions', sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'cared_person_institutions', type_='foreignkey')
    op.drop_index(op.f('ix_cared_person_institutions_status_type_id'), table_name='cared_person_institutions')
    op.drop_column('cared_person_institutions', 'status_type_id')
    # ### end Alembic commands ###
