"""normalize relationship_type in caregiver_institution

Revision ID: 89fb80343f59
Revises: 856efb6a597b
Create Date: 2025-07-06 00:20:38.908770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89fb80343f59'
down_revision: Union[str, None] = '856efb6a597b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('relationship_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_relationship_types_name'), 'relationship_types', ['name'], unique=True)
    op.add_column('caregiver_institutions', sa.Column('relationship_type_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_caregiver_institutions_relationship_type_id'), 'caregiver_institutions', ['relationship_type_id'], unique=False)
    op.create_foreign_key(None, 'caregiver_institutions', 'relationship_types', ['relationship_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'caregiver_institutions', type_='foreignkey')
    op.drop_index(op.f('ix_caregiver_institutions_relationship_type_id'), table_name='caregiver_institutions')
    op.drop_column('caregiver_institutions', 'relationship_type_id')
    op.drop_index(op.f('ix_relationship_types_name'), table_name='relationship_types')
    op.drop_table('relationship_types')
    # ### end Alembic commands ###
