"""normalize_status_fields_to_status_type_id

Revision ID: 9bfe8aac1714
Revises: 3b0b703f2d25
Create Date: 2025-07-04 22:00:42.960547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bfe8aac1714'
down_revision: Union[str, None] = '3b0b703f2d25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('status_type_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_alerts_status_type_id'), 'alerts', ['status_type_id'], unique=False)
    op.create_foreign_key(None, 'alerts', 'status_types', ['status_type_id'], ['id'])
    op.drop_column('alerts', 'status')
    op.add_column('billing_records', sa.Column('status_type_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_billing_records_status_type_id'), 'billing_records', ['status_type_id'], unique=False)
    op.create_foreign_key(None, 'billing_records', 'status_types', ['status_type_id'], ['id'])
    op.drop_column('billing_records', 'status')
    op.add_column('devices', sa.Column('status_type_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_devices_status_type_id'), 'devices', ['status_type_id'], unique=False)
    op.create_foreign_key(None, 'devices', 'status_types', ['status_type_id'], ['id'])
    op.drop_column('devices', 'status')
    op.add_column('user_package_add_ons', sa.Column('status_type_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_user_package_add_ons_status_type_id'), 'user_package_add_ons', ['status_type_id'], unique=False)
    op.create_foreign_key(None, 'user_package_add_ons', 'status_types', ['status_type_id'], ['id'])
    op.drop_column('user_package_add_ons', 'status')
    op.add_column('user_packages', sa.Column('status_type_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_user_packages_status_type_id'), 'user_packages', ['status_type_id'], unique=False)
    op.create_foreign_key(None, 'user_packages', 'status_types', ['status_type_id'], ['id'])
    op.drop_column('user_packages', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_packages', sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user_packages', type_='foreignkey')
    op.drop_index(op.f('ix_user_packages_status_type_id'), table_name='user_packages')
    op.drop_column('user_packages', 'status_type_id')
    op.add_column('user_package_add_ons', sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user_package_add_ons', type_='foreignkey')
    op.drop_index(op.f('ix_user_package_add_ons_status_type_id'), table_name='user_package_add_ons')
    op.drop_column('user_package_add_ons', 'status_type_id')
    op.add_column('devices', sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'devices', type_='foreignkey')
    op.drop_index(op.f('ix_devices_status_type_id'), table_name='devices')
    op.drop_column('devices', 'status_type_id')
    op.add_column('billing_records', sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'billing_records', type_='foreignkey')
    op.drop_index(op.f('ix_billing_records_status_type_id'), table_name='billing_records')
    op.drop_column('billing_records', 'status_type_id')
    op.add_column('alerts', sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'alerts', type_='foreignkey')
    op.drop_index(op.f('ix_alerts_status_type_id'), table_name='alerts')
    op.drop_column('alerts', 'status_type_id')
    # ### end Alembic commands ###
