"""add_reminder_types_table_and_normalize_reminder_type

Revision ID: a71fed7c31f1
Revises: 5c426b00feb0
Create Date: 2025-07-06 00:54:41.361434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a71fed7c31f1'
down_revision: Union[str, None] = '5c426b00feb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reminder_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('icon_name', sa.String(length=50), nullable=True),
    sa.Column('color_code', sa.String(length=7), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reminder_types_category'), 'reminder_types', ['category'], unique=False)
    op.create_index(op.f('ix_reminder_types_name'), 'reminder_types', ['name'], unique=True)
    op.add_column('reminders', sa.Column('reminder_type_id', sa.Integer(), nullable=False))
    op.drop_index('ix_reminders_reminder_type', table_name='reminders')
    op.create_index(op.f('ix_reminders_reminder_type_id'), 'reminders', ['reminder_type_id'], unique=False)
    op.create_foreign_key(None, 'reminders', 'reminder_types', ['reminder_type_id'], ['id'])
    op.drop_column('reminders', 'reminder_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reminders', sa.Column('reminder_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'reminders', type_='foreignkey')
    op.drop_index(op.f('ix_reminders_reminder_type_id'), table_name='reminders')
    op.create_index('ix_reminders_reminder_type', 'reminders', ['reminder_type'], unique=False)
    op.drop_column('reminders', 'reminder_type_id')
    op.drop_index(op.f('ix_reminder_types_name'), table_name='reminder_types')
    op.drop_index(op.f('ix_reminder_types_category'), table_name='reminder_types')
    op.drop_table('reminder_types')
    # ### end Alembic commands ###
