"""make package_id not null in devices

Revision ID: b270ee7261b2
Revises: c236806b2eb4
Create Date: 2025-07-13 23:42:34.299361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b270ee7261b2'
down_revision: Union[str, None] = 'c236806b2eb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('devices', 'package_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('devices', 'package_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
