"""add_event_types_table_and_normalize_event_type_in_event

Revision ID: b2d0afa29bf3
Revises: d3f9a01675d4
Create Date: 2025-07-06 00:47:43.002592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2d0afa29bf3'
down_revision: Union[str, None] = 'd3f9a01675d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('icon_name', sa.String(length=50), nullable=True),
    sa.Column('color_code', sa.String(length=7), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_types_category'), 'event_types', ['category'], unique=False)
    op.create_index(op.f('ix_event_types_name'), 'event_types', ['name'], unique=True)
    op.add_column('events', sa.Column('event_type_id', sa.Integer(), nullable=False))
    op.drop_index('ix_events_event_type', table_name='events')
    op.create_index(op.f('ix_events_event_type_id'), 'events', ['event_type_id'], unique=False)
    op.create_foreign_key(None, 'events', 'event_types', ['event_type_id'], ['id'])
    op.drop_column('events', 'event_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('event_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_index(op.f('ix_events_event_type_id'), table_name='events')
    op.create_index('ix_events_event_type', 'events', ['event_type'], unique=False)
    op.drop_column('events', 'event_type_id')
    op.drop_index(op.f('ix_event_types_name'), table_name='event_types')
    op.drop_index(op.f('ix_event_types_category'), table_name='event_types')
    op.drop_table('event_types')
    # ### end Alembic commands ###
