"""implement_ddl_cascade_delete_clean

Revision ID: b315a39aab9d
Revises: 7720cbe232ed
Create Date: 2025-07-19 03:29:07.599235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b315a39aab9d'
down_revision: Union[str, None] = '7720cbe232ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
