"""add_status_types_table

Revision ID: b8ddb6ba9fb2
Revises: 12c3b3281966
Create Date: 2025-07-04 21:48:04.808975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8ddb6ba9fb2'
down_revision: Union[str, None] = '12c3b3281966'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
