"""add package_id to devices

Revision ID: c236806b2eb4
Revises: merge_heads_fix_conflict
Create Date: 2025-07-13 23:37:33.864291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c236806b2eb4'
down_revision: Union[str, None] = 'merge_heads_fix_conflict'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('package_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_devices_package_id'), 'devices', ['package_id'], unique=False)
    op.create_foreign_key(None, 'devices', 'packages', ['package_id'], ['id'])
    op.drop_constraint('uq_status_types_name_category', 'status_types', type_='unique')
    op.create_index(op.f('ix_status_types_name'), 'status_types', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_status_types_name'), table_name='status_types')
    op.create_unique_constraint('uq_status_types_name_category', 'status_types', ['name', 'category'])
    op.drop_constraint(None, 'devices', type_='foreignkey')
    op.drop_index(op.f('ix_devices_package_id'), table_name='devices')
    op.drop_column('devices', 'package_id')
    # ### end Alembic commands ###
