"""add_alert_types_table_and_normalize_alert_type_in_alert

Revision ID: d3f9a01675d4
Revises: 89132281342a
Create Date: 2025-07-06 00:43:47.134186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3f9a01675d4'
down_revision: Union[str, None] = '89132281342a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('icon_name', sa.String(length=50), nullable=True),
    sa.Column('color_code', sa.String(length=7), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_types_category'), 'alert_types', ['category'], unique=False)
    op.create_index(op.f('ix_alert_types_name'), 'alert_types', ['name'], unique=True)
    op.add_column('alerts', sa.Column('alert_type_id', sa.Integer(), nullable=False))
    op.drop_index('ix_alerts_alert_type', table_name='alerts')
    op.create_index(op.f('ix_alerts_alert_type_id'), 'alerts', ['alert_type_id'], unique=False)
    op.create_foreign_key(None, 'alerts', 'alert_types', ['alert_type_id'], ['id'])
    op.drop_column('alerts', 'alert_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('alert_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'alerts', type_='foreignkey')
    op.drop_index(op.f('ix_alerts_alert_type_id'), table_name='alerts')
    op.create_index('ix_alerts_alert_type', 'alerts', ['alert_type'], unique=False)
    op.drop_column('alerts', 'alert_type_id')
    op.drop_index(op.f('ix_alert_types_name'), table_name='alert_types')
    op.drop_index(op.f('ix_alert_types_category'), table_name='alert_types')
    op.drop_table('alert_types')
    # ### end Alembic commands ###
