"""add_service_types_table_and_normalize_service_type_fields

Revision ID: dfb5939c5d29
Revises: 4d6d44bd1ed4
Create Date: 2025-07-06 00:30:03.284005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfb5939c5d29'
down_revision: Union[str, None] = '4d6d44bd1ed4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_types_category'), 'service_types', ['category'], unique=False)
    op.create_index(op.f('ix_service_types_name'), 'service_types', ['name'], unique=True)
    op.add_column('cared_person_institutions', sa.Column('service_type_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'cared_person_institutions', 'service_types', ['service_type_id'], ['id'])
    op.drop_column('cared_person_institutions', 'service_type')
    op.add_column('caregiver_reviews', sa.Column('service_type_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'caregiver_reviews', 'service_types', ['service_type_id'], ['id'])
    op.drop_column('caregiver_reviews', 'service_type')
    op.add_column('institution_reviews', sa.Column('service_type_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'institution_reviews', 'service_types', ['service_type_id'], ['id'])
    op.drop_column('institution_reviews', 'service_type')
    op.drop_column('institution_reviews', 'length_of_stay')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('institution_reviews', sa.Column('length_of_stay', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('institution_reviews', sa.Column('service_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'institution_reviews', type_='foreignkey')
    op.drop_column('institution_reviews', 'service_type_id')
    op.add_column('caregiver_reviews', sa.Column('service_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'caregiver_reviews', type_='foreignkey')
    op.drop_column('caregiver_reviews', 'service_type_id')
    op.add_column('cared_person_institutions', sa.Column('service_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'cared_person_institutions', type_='foreignkey')
    op.drop_column('cared_person_institutions', 'service_type_id')
    op.drop_index(op.f('ix_service_types_name'), table_name='service_types')
    op.drop_index(op.f('ix_service_types_category'), table_name='service_types')
    op.drop_table('service_types')
    # ### end Alembic commands ###
